### ISSUE TITLE
White screen after login screen

### ISSUE THREAD

**Issue by idRem7** [FinTecSystems/xs2a-react-native#4]
Hi!

I have block white screen on Anrdoid 8 and 11
1. I did provide wizard key from my server (key is correct)
2. Open FinTech SDK from view component (follow guide)
3. Fintech sdk login screen opens
4. Input login 'testbank', psw '12345678' (allow any сredentials)
5. Loading spinner opens
6. Empty white screen appers after ~1-2sec and don't hide, show long time

This case dont repeat on Android 6 and any iOS

<img width="374" alt="Screenshot 2022-07-28 at 20 42 54" src="https://user-images.githubusercontent.com/18027252/181581394-916282ba-10c1-4c3d-b309-6e83bd0791ce.png">
<img width="1062" alt="Screenshot 2022-07-28 at 20 45 25" src="https://user-images.githubusercontent.com/18027252/181581402-8a19a731-8f50-4d53-86f0-39c4a1661781.png">
<img width="1062" alt="Screenshot 2022-07-28 at 20 48 40" src="https://user-images.githubusercontent.com/18027252/181581746-b3f3572b-6bf4-4c6b-8f91-a791d1974e94.png">

**Comment by idRem7** [comment]
Mistake, on 6 and 11 Android

**Comment by maik-mursall** [comment]
Hi @idRem7,
sorry for the late response ^^".

Is this Issue still occurring in the latest version of the SDK?

If that's the case, can you provide me all props you've set on the `Xs2aReactNativeViewManager`?
Because it's normal for the component to show nothing, if the transaction succeeded, maybe you
didn't register the `onSuccess` callback?

I look forward hearing from you!

**Comment by idRem7** [comment]
Thx for answer!

In present this problem does not reproduce. We don't know why...

![Screenshot 2022-08-17 at 13 37 23](https://user-images.githubusercontent.com/18027252/185679084-59e4bc4b-2bd1-443a-a114-c1a200e43b5a.png)
![Screenshot 2022-08-17 at 13 37 32](https://user-images.githubusercontent.com/18027252/185679101-1faf1d21-abd0-4bdf-9fd3-c6cf3671baf9.png)

**Comment by maik-mursall** [comment]
Everything in the config looks good to me so far at least.
Please let me know when the Issue occurs again :)
